[default]
SERVER_URL = "http://localhost"
SERVER_PORT = 5070
SERVER_API = "/api"
USERNAME = "gamma-user"
CI_MODE = false

[development]
# In development you might override CI_MODE or other values


[ci]
SERVER_URL = "http://localhost"
SERVER_PORT = 5070
SERVER_API = "/api"
USERNAME = "gamma-user"
CI_MODE = true