name: Infrastructure Setup

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      python_version:
        required: true
        type: string
      vantage6_version:
        required: true
        type: string
    # secrets:
    #   INFRA_TOKEN:
    #     required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v3
      - name: Setup Infrastructure
        run: |
            chmod +x shutdown.sh
            # Add more parameters from the matrix test
            echo "Setting up infrastructure for environment: ${{ inputs.environment }}"
            echo "Using Python version: ${{ inputs.python_version }}"
            echo "Using vantage6 version: ${{ inputs.vantage6_version }}"
            # Example: run your setup script with these parameters
            ENVIRONMENT=${{ inputs.environment }} \
            PYTHON_INTERPRETER=python${{ inputs.python_version }} \
            VERSION_VANTAGE6=${{ inputs.vantage6_version }} \
            ./shutdown.sh
        working-directory: infrastructure

