name: Vantage6 Infrastructure Test

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  vantage6-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Prepare and run setup
        run: |
          cd infrastructure
          chmod +x setup.sh shutdown.sh
          # (Optional) Show scripts for debugging
          # cat setup.sh
          ENVIRONMENT=CI ./setup.sh

      - name: Check that containers are running
        run: docker ps

      - name: Infrastructure Tests
        run: |
          cd infrastructure_tests
          for script in *.sh; do
            echo "Running test script: $script"
            chmod +x "$script"
            ./"$script"
          done

      - name: Tear down vantage6
        run: |
          cd infrastructure
          ENVIRONMENT=CI ./shutdown.sh

      - name: Confirm containers are removed
        run: docker ps -a
