name: Vantage6 Compatibility Matrix

on:
  workflow_dispatch:

jobs:
  vantage6-matrix:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        vantage6-version: ["4.14.0", "latest"]

    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      ENVIRONMENT: CI
      UI_ENABLED: false

    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ matrix.python-version }}

      - name: Define vantage6 version
        run: echo "VERSION_VANTAGE6=${{ matrix['vantage6-version'] }}" >> $GITHUB_ENV

      - name: Preflight
        run: |
          chmod +x infra.sh setup.sh shutdown.sh
          PYTHON_INTERPRETER=python${{ matrix['python-version'] }} ./infra.sh preflight
        working-directory: infrastructure

      - name: Start infrastructure
        run: |
          PYTHON_INTERPRETER=python${{ matrix['python-version'] }} ./infra.sh up
        working-directory: infrastructure

      - name: Run infrastructure tests
        run: |
          PYTHON_INTERPRETER=python${{ matrix['python-version'] }} ./infra.sh test
        working-directory: infrastructure

      - name: Shutdown vantage6
        if: always()
        run: |
          PYTHON_INTERPRETER=python${{ matrix['python-version'] }} ./infra.sh down
        working-directory: infrastructure

      - name: Confirm containers are removed
        if: always()
        run: docker ps -a
